### ISSUE TITLE
Issue using gem

### ISSUE THREAD

**Issue by kevinjalbert** [need47/fselector#3]
I installed _r_ and then the gem and when I `require `fselector``, I get the following error as shown in this **[gist](https://gist.github.com/2942869)**.

I have the same error using Arch Linux and Ubuntu, I also was using Ruby 1.9.3.

Is this a bug, or something wrong/missing on my system?

**Comment by AmirHooshangi** [comment]
> I installed _r_ and then the gem and when I `require `fselector``, I get the following error as shown in this **[gist](https://gist.github.com/2942869)**.
> 
> I have the same error using Arch Linux and Ubuntu, I also was using Ruby 1.9.3.
> 
> Is this a bug, or something wrong/missing on my system?

Your gist has been removed but I guess you have a same issue like me:
https://github.com/need47/fselector/issues/4

**Comment by kevinjalbert** [comment]
I’ve completely forgotten about this issue, and like you’ve said I’ve cleaned out some old gists I made.

It sounds like #4  supersedes this one and so I’ll close this out.
